### ISSUE TITLE
Source code not included in release 1.0.0.

### ISSUE THREAD

**Issue by ghost** [heyjoeway/s2cx#2]
If you download the source code from [1.0.0](https://github.com/heyjoeway/s2cx/releases/tag/1.0.0), you just get 2 empty folders and the (useless) readme. You can clone the repository, but it would be a good idea to keep the source code there for archival reasons.

**Comment by heyjoeway** [comment]
That's GitHub's problem, not mine. The source code to the hack and the emulator are included as submodules, and GitHub chooses not to include them in the release sources. If you want to download the sources as ZIPs, you'll have to visit the individual repositories and download them there. The current commit of this repository should link to the release commits of each submodule.

**Comment by heyjoeway** [comment]
That being said, even those you'll probably just want to clone using Git. The emulator itself has submodules that are required for building and downloading a ZIP from GitHub won't include those either. Gonna go on a rant here but GitHub shouldn't even give the option to download stuff as ZIPs considering how effed up it is. I had this same issue when I used Git LFS to store files for ICBINS.
